server:
  error:
    include-message: always
blogapi:
  driverClassName: "com.mysql.cj.jdbc.Driver"
  dataBaseUrl: "jdbc:mysql://localhost:3306/blog_app"
  dataUsername: "blogadmin"
  dataPassword: "secretpass"